apiVersion: v1
kind: Service
metadata:
  name: front-end-svc
  labels:
    app: front-end
spec:
  type: ClusterIP
  selector:
    app: front-end
  ports:
  - name: front-end-svc
    port: 80
    targetPort: 3000
