namespace: node-app
# commonLabels:
#   app: node-app
resources:
  - ../../base/apps/be
  - ../../base/apps/fe
  - ../../base/apps/mongo
  - be-ingress.yaml
  - fe-ingress.yaml
  - be-cm.yaml
patchesStrategicMerge:
  - be-deploy.yaml
  - fe-deploy.yaml
images:
  - name: sami203/e-commerce-front-end
    newTag: a7f3ddea94b4a623abf8bc4624757822ab94c5d1
  - name: sami203/e-commerce-back-end
    newTag: 53fa7760c55a503a1d7932cff8047a593bc5da04
