namespace: node-app
# commonLabels:
#   app: node-app
resources:
  - ../../base/apps/be
  - ../../base/apps/fe
  - ../../base/apps/mongo
  - be-ingress.yaml
  - fe-ingress.yaml
patchesStrategicMerge:
  - be-deploy.yaml
  - fe-deploy.yaml
images:
  - name: sami203/e-commerce-front-end
    newTag: 19623a69e6b51f17568ceed87cd5324274377540
  - name: sami203/e-commerce-back-end
    newTag: 701e32a54ffa0fe3435e368d3f470c8e0290d0d1