apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
            secretKeyRef: 
              name: mongo-sectets
              key: mongo-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
            secretKeyRef: 
              name: mongo-sectets
              key: mongo-password
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-claim